package lbr2048.currencyconverter.network

import com.squareup.moshi.Json
import lbr2048.currencyconverter.Currency

data class Rates(
    @Json(name = "AUD") var AUD: Double? = null,
    @Json(name = "BGN") var BGN: Double? = null,
    @Json(name = "BRL") var BRL: Double? = null,
    @Json(name = "CAD") var CAD: Double? = null,
    @Json(name = "CHF") var CHF: Double? = null,
    @Json(name = "CNY") var CNY: Double? = null,
    @Json(name = "CZK") var CZK: Double? = null,
    @Json(name = "DKK") var DKK: Double? = null,
    @Json(name = "GBP") var GBP: Double? = null,
    @Json(name = "HKD") var HKD: Double? = null,
    @Json(name = "HRK") var HRK: Double? = null,
    @Json(name = "HUF") var HUF: Double? = null,
    @Json(name = "IDR") var IDR: Double? = null,
    @Json(name = "ILS") var ILS: Double? = null,
    @Json(name = "INR") var INR: Double? = null,
    @Json(name = "ISK") var ISK: Double? = null,
    @Json(name = "JPY") var JPY: Double? = null,
    @Json(name = "KRW") var KRW: Double? = null,
    @Json(name = "MXN") var MXN: Double? = null,
    @Json(name = "MYR") var MYR: Double? = null,
    @Json(name = "NOK") var NOK: Double? = null,
    @Json(name = "NZD") var NZD: Double? = null,
    @Json(name = "PHP") var PHP: Double? = null,
    @Json(name = "PLN") var PLN: Double? = null,
    @Json(name = "RON") var RON: Double? = null,
    @Json(name = "RUB") var RUB: Double? = null,
    @Json(name = "SEK") var SEK: Double? = null,
    @Json(name = "SGD") var SGD: Double? = null,
    @Json(name = "THB") var THB: Double? = null,
    @Json(name = "USD") var USD: Double? = null,
    @Json(name = "ZAR") var ZAR: Double? = null
) {

    fun getRatesMap(): Map<String, Double?> = mapOf(
        "EUR" to 1.0,
        "AUD" to AUD,
        "BGN" to BGN,
        "BRL" to BRL,
        "CAD" to CAD,
        "CHF" to CHF,
        "CNY" to CNY,
        "CZK" to CZK,
        "DKK" to DKK,
        "GBP" to GBP,
        "HKD" to HKD,
        "HRK" to HRK,
        "HUF" to HUF,
        "IDR" to IDR,
        "ILS" to ILS,
        "INR" to INR,
        "ISK" to ISK,
        "JPY" to JPY,
        "KRW" to KRW,
        "MXN" to MXN,
        "MYR" to MYR,
        "NOK" to NOK,
        "NZD" to NZD,
        "PHP" to PHP,
        "PLN" to PLN,
        "RON" to RON,
        "RUB" to RUB,
        "SEK" to SEK,
        "SGD" to SGD,
        "THB" to THB,
        "USD" to USD,
        "ZAR" to ZAR
    )

    fun getRates(): List<Currency> = listOf(
        Currency(id = "EUR", value = 1.0),
        Currency(id = "AUD", value = AUD!!),
        Currency(id = "BGN", value = BGN!!),
        Currency(id = "BRL", value = BRL!!),
        Currency(id = "CAD", value = CAD!!),
        Currency(id = "CHF", value = CHF!!),
        Currency(id = "CNY", value = CNY!!),
        Currency(id = "CZK", value = CZK!!),
        Currency(id = "DKK", value = DKK!!),
        Currency(id = "GBP", value = GBP!!),
        Currency(id = "HKD", value = HKD!!),
        Currency(id = "HRK", value = HRK!!),
        Currency(id = "HUF", value = HUF!!),
        Currency(id = "IDR", value = IDR!!),
        Currency(id = "ILS", value = ILS!!),
        Currency(id = "INR", value = INR!!),
        Currency(id = "ISK", value = ISK!!),
        Currency(id = "JPY", value = JPY!!),
        Currency(id = "KRW", value = KRW!!),
        Currency(id = "MXN", value = MXN!!),
        Currency(id = "MYR", value = MYR!!),
        Currency(id = "NOK", value = NOK!!),
        Currency(id = "NZD", value = NZD!!),
        Currency(id = "PHP", value = PHP!!),
        Currency(id = "PLN", value = PLN!!),
        Currency(id = "RON", value = RON!!),
        Currency(id = "RUB", value = RUB!!),
        Currency(id = "SEK", value = SEK!!),
        Currency(id = "SGD", value = SGD!!),
        Currency(id = "THB", value = THB!!),
        Currency(id = "USD", value = USD!!),
        Currency(id = "ZAR", value = ZAR!!)
    )
}